### ISSUE TITLE
App Not Verified Warning

### ISSUE THREAD

**Issue by clairehjk** [pizza442/BeatTheLag#12]
After signing in, I'm immediately seeing a warning from my browser: "This app hasn't been verified by Google yet. Only proceed if you know and trust the developer." 
Related to security, I'm not sure what's causing this, but it is alarming for a user. 
 
*I am using Firefox*
1. Sign in with Google
2. See warning page

**Comment by VanelyRuiz** [comment]
Fixed in commit: https://github.com/pizza442/BeatTheLag/commit/f54ed2da2c05364e82fc336a416b9a6226269b9c

Sorry about that, our original plan was to add events to a user's Google Calendar, but that turned out to be complicated. We would've had to get verified by Google because accessing a user's Google Calendar is a sensitive scope. The verification process takes weeks, so we decided it was out of the scope of this project. When removing the Google Calendar scope from our project, I missed one line of code that added the calendar scope to our authentication process. This resulted in Google notifying you that we were not verified; however, without being verified we could not access a user's Google Calendar unless they were a member of our Google Project. We apologize for the warning.
