### ISSUE TITLE
No back button or start over button

### ISSUE THREAD

**Issue by emilytao19** [pizza442/BeatTheLag#2]
After submitting my request there is no way for me to go back or start over 
<img width="992" alt="Screen Shot 2019-06-10 at 4 09 53 PM" src="https://user-images.githubusercontent.com/32439428/59232679-47f56600-8b9a-11e9-83bb-688e12e22ea1.png">

**Comment by s21dy** [comment]
Thank you for the feedback!
This maybe a possible if we get time. Yet, our consideration is that the go back and start over feature require our team to modify several components in our system. This includes either input handler or schedule generator will have to store the previous input to data manager and then data manager will send it back the information to input handler again. 
The required features may change our data structure and it have a really high chance that we have to change the whole thing in order to have these features. 
Due to the high chance of overall updated and costing large amount of time, out team have decided that not implement go back and start over.   

Yet instead we have create the [NEW] button if user want to create the new calendar. 
See commit faa01fd86e4ba43cd6c7637c83af5d2c887a3962
