### ISSUE TITLE
Regardless of end date, the result is the same

### ISSUE THREAD

**Issue by dayoungcheong** [pizza442/BeatTheLag#5]
There is also no point in the end date query because regardless of the end date, the results are exactly the same. It seems confusing why this is even asked in the first place if it is not included in any calculations

**Comment by s21dy** [comment]
Thank you for the feedback.
We included the end date input originally because we thought we were going to use this date in our algorithm. Yet, it turned out we don't have to deal the case that would utilize this date. But since it didn't affect our functionality and it is specify in our spec, we decided to leave this feature here.
Thanks again.
