### ISSUE TITLE
Schedule is not added into GoogleCalendar automatically

### ISSUE THREAD

**Issue by rheaxychen** [pizza442/BeatTheLag#9]
![Screen Shot 2019-06-10 at 7 40 26 PM](https://user-images.githubusercontent.com/24926110/59239816-b5fc5600-8bb7-11e9-9826-446296639d37.png)
After creating a lag schedule for trip _From 2019-06-09 at 22:00 till 2019-06-10 at 08:00_, nothing shows up on the google calendar as described by the development team (see the screenshot ^).

**Comment by VanelyRuiz** [comment]
![image](https://user-images.githubusercontent.com/35097969/59253976-2e790c00-8be4-11e9-9fa9-822f4ace4ab6.png)
**Our description does not say it will add events to Google Calendar.**

We removed this requirement from our 1.0 version because adding events to a user's Google Calendar is a sensitive scope that requires verification from Google. Unfortunately, the verification process could take weeks, and without it our app would be unusable to people outside of our development team. Due to the length of this project, it was not feasible.
